# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSModuleDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iOSModuleDemo
  pod 'CTMediator-ZW'
  pod 'Masonry'
  pod 'BeeHive'
  pod 'CTMediatorModule',:path=>'../CTMediatorModule'
  pod 'BeeHiveModule',:path=>'../BeeHiveModule'
  
  target 'iOSModuleDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSModuleDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
